export const USER_SIGNIN_SAGA = 'USER_SIGNIN_SAGA'


export const USER_SIGN_IN_API = 'USER_SIGN_IN_API'





export const USLOGIN = 'USLOGIN'



export const GET_DATA_PROJECT_CATEGORY = 'GET_DATA_PROJECT_CATEGORY'

export const GET_ALL_PROJECT_SAGA = 'GET_ALL_PROJECT_SAGA'
export const CREATE_PROJECT_SAGA = 'CREATE_PROJECT_SAGA'


export const GET_LIST_PROJECT = 'GET_LIST_PROJECT'
export const GET_ALL_PROJECT = 'GET_ALL_PROJECT'



export const GET_PROJECT_DETAIL_SAGA = 'GET_PROJECT_DETAIL_SAGA'



export const DELETE_PROJECT = 'DELETE_PROJECT'


export const EDIT_PROJECT = 'EDIT_PROJECT'

export const SUBMIT_EDIT_PROJECT = 'SUBMIT_EDIT_PROJECT'
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION'

export const GET_USER = 'GET_USER'
export const GET_USER_LIST = 'GET_USER_LIST'


export const ADD_NEW_USER = 'ADD_NEW_USER'



export const REMOVE_USER_FROM_PROJECT = 'REMOVE_USER_FROM_PROJECT'

export const LIST_TASK_FROM_API = 'LIST_TASK_FROM_API'


export const CREATE_BUG = 'CREATE_BUG'




export const GET_ALL_PROJECT_INFOR = 'GET_ALL_PROJECT_INFOR'

export const GET_ALL_PROJECT_INFOR_SAGA = 'GET_ALL_PROJECT_INFOR_SAGA'


export const GET_ALL_TASK_TYPE = ' GET_ALL_TASK_TYPE'

export const GET_ALL_TASK_TYPE_SAGA = 'GET_ALL_TASK_TYPE_SAGA'


export const GET_PRIORITY_SAGA = 'GET_PRIORITY_SAGA'
export const GET_PRIORITY_REDUCER = 'GET_PRIORITY_REDUCER'

export const GET_ALL_STATUS_SAGA = 'GET_ALL_STATUS_SAGA'
export const GET_ALL_STATUS_REDUCER = 'GET_ALL_STATUS_REDUCER'


export const CREATE_NEW_TASK_SAGA = 'CREATE_NEW_TASK_SAGA'
export const CREATE_NEW_TASK_REDUCER = 'CREATE_NEW_TASK_REDUCER'


export const GET_USER_BY_PROJECT = 'GET_USER_BY_PROJECT'
export const  GET_USER_BY_PROJECT_SAGA = ' GET_USER_BY_PROJECT_SAGA'

export const SET_SUBMIT_PROJECT = 'SET_SUBMIT_PROJECT'


export const GET_DETAIL_TASK = 'GET_DETAIL_TASK'


export const GET_TASK_DETAIL_SAGA = 'GET_TASK_DETAIL_SAGA'
export const GET_TASK_DETAIL_REDUCER = 'GET_TASK_DETAIL_REDUCER'


export const UPDATE_TASK_STATUS_SAGA = 'UPDATE_TASK_STATUS_SAGA'
export const UPDATE_TASK_STATUS_REDUCER = 'UPDATE_TASK_STATUS'


export const UPDATE_TASK_DETAIL_REDUCER = 'UPDATE_TASK_DETAIL_REDUCER'

export const CHANGE_TASK_MODAL = 'CHANGE_TASK_MODAL'



export const UPDATAE_TASK_SAGA = 'UPDATAE_TASK_SAGA'
export const UPDATE_TASK_TO_REDUCER = 'UPDATE_TASK_TO_REDUCER'